# Setup env

In [1]:
import pandas as pd
from pathlib import Path

In [23]:
# Get the absolute path of where you are right now
src_path = Path.cwd()
project_src = src_path.parents[1]
print(f"Your project source root is: {project_src}")

# Set 100 rows to display
pd.set_option('display.max_rows', 100) # Set it higher than your 80 rows

Your project source root is: c:\Users\davib\Desktop\MSc_DataScience\DataWarehouse\lab_assignment\imbd

# Read Silver Layer

In [3]:
# Read dims
# bridge_profession_group = pd.read_parquet(f'{project_src}\\data\\silver\\bridge_profession_group.parquet')
# dim_profession = pd.read_parquet(f'{project_src}\\data\\silver\\dim_profession.parquet')
dim_person = pd.read_parquet(f'{project_src}\\data\\silver\\dim_person.parquet')
# dim_roles = pd.read_parquet(f'{project_src}\\data\\silver\\dim_roles.parquet')
# dim_genres = pd.read_parquet(f'{project_src}\\data\\silver\\dim_genres.parquet')
bridge_genres = pd.read_parquet(f'{project_src}\\data\\silver\\bridge_genres.parquet')
dim_title_basic = pd.read_parquet(f'{project_src}\\data\\silver\\dim_title_basic.parquet')
bridge_kwn_titles = pd.read_parquet(f'{project_src}\\data\\silver\\bridge_kwn_titles.parquet')

# Read fact tables
participations_pers = pd.read_parquet(f'{project_src}\\data\\silver\\participations_pers.parquet')

# Transformations to prepare final data for gold

Analysis to be done:
- Who are the most active people in the film industry? (more participations) OK
- What are the actors with more runtime done? (more runtime considering the participations) OK
- What are the participants with more known participations? (more known titles) NOK
- What are the participants which have worked in more distinct genres? ~~

In [5]:
## Data Structure Exploration

In [10]:
# Explore key tables
print("participations_pers columns:", participations_pers.columns.tolist())
print("dim_person columns:", dim_person.columns.tolist())
print("dim_title_basic columns:", dim_title_basic.columns.tolist())
print("bridge_genres columns:", bridge_genres.columns.tolist())
print("bridge_kwn_titles columns:", bridge_kwn_titles.columns.tolist())
# print("dim_genres columns:", dim_genres.columns.tolist())
# print("dim_roles columns:", dim_roles.columns.tolist())

participations_pers columns: ['nconst', 'primaryName', 'tconst', 'titleType', 'primaryTitle', 'genre_group_id', 'category', 'job', 'characters', 'profession_group_id', 'kwn_title_group_id']
dim_person columns: ['nconst', 'primaryName', 'birthYear', 'deathYear', 'profession_group_id', 'weighting_factor_prf']
dim_title_basic columns: ['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear', 'endYear', 'runtimeMinutes', 'genre_group_id']
bridge_genres columns: ['tconst', 'genre_id', 'genre_group_id', 'weighting_factor_gen']
bridge_kwn_titles columns: ['tconst', 'nconst', 'kwn_title_group_id', 'weighting_factor_grp']

# Filter only movies and tvSeries

## Analysis 1: Most Active People (More Participations)

In [5]:
participations_pers['titleType'].unique()

<ArrowStringArray>
['movie', 'tvSeries']
Length: 2, dtype: str

In [52]:
# Filter for relevant title types
# most_active_people = participations_pers[participations_pers['titleType'].isin(['movie', 'tvSeries'])]

# Count total participations per person and titleType
counts = (
    participations_pers.groupby(['nconst', 'titleType'])
    .size()
    .reset_index(name='total_participations')
)

# Sort by count and then take the top 10 for each titleType
top_10_per_type = (
    counts.sort_values(['titleType', 'total_participations'], ascending=[True, False])
    .groupby('titleType')
    .head(10)
    .merge(dim_person[['nconst', 'primaryName', 'birthYear', 'deathYear']], on='nconst', how='left')
)

top_10_per_type_known =top_10_per_type.merge(bridge_kwn_titles, on='nconst', how='left').merge(dim_title_basic[['tconst', 'primaryTitle', 'isAdult']], on='tconst', how='left')
top_10_per_type_known = top_10_per_type_known[['primaryName', 'total_participations', 'titleType', 'birthYear', 'deathYear', 'primaryTitle', 'isAdult']]
# Display the results
# print("Top 10 Most Active People per Category:")
# print(top_10_per_type[['titleType', 'primaryName', 'total_participations']])
top_10_per_type_known.to_parquet(f'{project_src}\\data\\gold\\active_film_participants.parquet', index=False)

In [24]:
top_10_per_type_known.head(80)

,primaryName,total_participations,titleType,birthYear,deathYear,primaryTitle,isAdult
0,Ilaiyaraaja,1006,movie,1943,<NA>,Sagara Sangamam,0.0
1,Ilaiyaraaja,1006,movie,1943,<NA>,Thalapathi,0.0
2,Ilaiyaraaja,1006,movie,1943,<NA>,Kerala Varma Pazhassi Raja,0.0
3,Ilaiyaraaja,1006,movie,1943,<NA>,Tharai Thappattai,0.0
4,Shôji Sakai,1001,movie,<NA>,<NA>,Tokyo Booty Nights,1.0
5,Shôji Sakai,1001,movie,<NA>,<NA>,Nausicaä of the Valley of the Wind,0.0
6,Shôji Sakai,1001,movie,<NA>,<NA>,The Strawberries and the Gun,1.0
7,Shôji Sakai,1001,movie,<NA>,<NA>,Sexy S.W.A.T. Team,0.0
8,Brahmanandam,807,movie,1956,<NA>,Ready,0.0
9,Brahmanandam,807,movie,1956,<NA>,Dookudu,0.0
10,Brahmanandam,807,movie,1956,<NA>,Athadu,0.0
11,Brahmanandam,807,movie,1956,<NA>,Sarrainodu,0.0
12,Adoor Bhasi,590,movie,1929,1990,Acharam Ammini Osaram Omana,0.0
13,Adoor Bhasi,590,movie,1929,1990,Raagam,0.0
14,Adoor Bhasi,590,movie,1929,1990,Athirathram,0.0
15,Adoor Bhasi,590,movie,1929,1990,Kodiyettam,0.0
16,Matsunosuke Onoe,562,movie,1875,1926,Araki Mataemon,0.0
17,Matsunosuke Onoe,562,movie,1875,1926,Kunisada Chûji,0.0
18,Matsunosuke Onoe,562,movie,1875,1926,NaN,NaN
19,Matsunosuke Onoe,562,movie,1875,1926,Yajîkita: zenpen,0.0
20,Eddie Garcia,542,movie,1929,2019,Magdusa ka!,0.0
21,Eddie Garcia,542,movie,1929,2019,Saan nagtatago ang pag-ibig?,0.0
22,Eddie Garcia,542,movie,1929,2019,Atsay,0.0
23,Eddie Garcia,542,movie,1929,2019,Sinasamba kita,0.0
24,William Shakespeare,529,movie,1564,1616,Romeo and Juliet: The War,0.0
25,William Shakespeare,529,movie,1564,1616,M the Movie,0.0
26,William Shakespeare,529,movie,1564,1616,Macbeth,0.0
27,William Shakespeare,529,movie,1564,1616,Much Ado,0.0
28,Dong-Chun Hyeon,514,movie,<NA>,<NA>,Korean National Flower,0.0
29,Dong-Chun Hyeon,514,movie,<NA>,<NA>,Three Robot Heroes,0.0
30,Dong-Chun Hyeon,514,movie,<NA>,<NA>,Horimsa Temple,0.0
31,Dong-Chun Hyeon,514,movie,<NA>,<NA>,Death Song,0.0
32,Hui-su Kim,512,movie,<NA>,<NA>,The Contintental Spy,0.0
33,Hui-su Kim,512,movie,<NA>,<NA>,Donghak nan,0.0
34,Hui-su Kim,512,movie,<NA>,<NA>,Hot Wind,0.0
35,Hui-su Kim,512,movie,<NA>,<NA>,A Dangerous Youth,0.0
36,Laxmikant Shantaram Kudalkar,467,movie,1937,1998,Eternal Sunshine of the Spotless Mind,0.0
37,Laxmikant Shantaram Kudalkar,467,movie,1937,1998,Karz,0.0
38,Laxmikant Shantaram Kudalkar,467,movie,1937,1998,Sargam,0.0
39,Laxmikant Shantaram Kudalkar,467,movie,1937,1998,Milan,0.0
40,Frank Welker,153,tvSeries,1946,<NA>,Transformers: Age of Extinction,0.0
41,Frank Welker,153,tvSeries,1946,<NA>,Transformers: Dark of the Moon,0.0
42,Frank Welker,153,tvSeries,1946,<NA>,Mortal Kombat,0.0
43,Frank Welker,153,tvSeries,1946,<NA>,Transformers: The Last Knight,0.0
44,Monica Rial,130,tvSeries,1975,<NA>,My Hero Academia,0.0
45,Monica Rial,130,tvSeries,1975,<NA>,Dragon Ball Super,0.0
46,Monica Rial,130,tvSeries,1975,<NA>,Dragon Ball Super: Broly,0.0
47,Monica Rial,130,tvSeries,1975,<NA>,Gen: Lock,0.0
48,Luci Christian,126,tvSeries,1973,<NA>,Gatchaman The Movie,0.0
49,Luci Christian,126,tvSeries,1973,<NA>,Appleseed Ex Machina,0.0
50,Luci Christian,126,tvSeries,1973,<NA>,Vampire Hunter D,0.0
51,Luci Christian,126,tvSeries,1973,<NA>,Ef: A Tale of Memories.,0.0
52,Don Messick,105,tvSeries,1926,1997,The Smurfs,0.0
53,Don Messick,105,tvSeries,1926,1997,Pufnstuf,0.0
54,Don Messick,105,tvSeries,1926,1997,The Jetsons,0.0
55,Don Messick,105,tvSeries,1926,1997,The Last Unicorn,0.0
56,Taissia Shanti,105,tvSeries,1992,<NA>,Club Seventeen,1.0
57,Taissia Shanti,105,tvSeries,1992,<NA>,Evil Angel,1.0
58,Taissia Shanti,105,tvSeries,1992,<NA>,College Fuck Parties,1.0
59,Taissia Shanti,105,tvSeries,1992,<NA>,Miss Shanti,1.0
60,Tom Kenny,101,tvSeries,1962,<NA>,Transformers: Revenge of the Fallen,0.0
61,Tom Kenny,101,tvSeries,1962,<NA>,SpongeBob SquarePants,0.0
62,Tom Kenny,101,tvSeries,1962,<NA>,The SpongeBob Movie: Sponge Out of Water,0.0
63,Tom Kenny,101,tvSeries,1962,<NA>,Transformers: Dark of the Moon,0.0
64,Mark Chinnery,99,tvSeries,1969,<NA>,Miracle Experiences! Unbelievable,0.0
65,Mark Chinnery,99,tvSeries,1969,<NA>,"Fly, Dakota, Fly!",0.0
66,Mark Chinnery,99,tvSeries,1969,<NA>,NaN,NaN
67,Mark Chinnery,99,tvSeries,1969,<NA>,Catch the Wave Kodawari Navi,0.0
68,Grey Griffin,92,tvSeries,1973,<NA>,NaN,NaN
69,Grey Griffin,92,tvSeries,1973,<NA>,NaN,NaN
70,Grey Griffin,92,tvSeries,1973,<NA>,When Marnie Was There,0.0
71,Grey Griffin,92,tvSeries,1973,<NA>,Transformers: Revenge of the Fallen,0.0
72,Dee Bradley Baker,88,tvSeries,1962,<NA>,Phineas and Ferb,0.0
73,Dee Bradley Baker,88,tvSeries,1962,<NA>,The SpongeBob SquarePants Movie,0.0
74,Dee Bradley Baker,88,tvSeries,1962,<NA>,American Dad!,0.0
75,Dee Bradley Baker,88,tvSeries,1962,<NA>,Space Jam,0.0
76,Rob Paulsen,88,tvSeries,1956,<NA>,Jimmy Neutron: Boy Genius,0.0
77,Rob Paulsen,88,tvSeries,1956,<NA>,Pinky and the Brain,0.0
78,Rob Paulsen,88,tvSeries,1956,<NA>,Tales of the Teenage Mutant Ninja Turtles,0.0
79,Rob Paulsen,88,tvSeries,1956,<NA>,Animaniacs,0.0

## Analysis 2: Actors with More Runtime Done

In [62]:
# Actors with more runtime: Sum runtime from all participations
actors_runtime = (
    participations_pers.merge(
        dim_title_basic[['tconst', 'runtimeMinutes']], 
        on='tconst', 
        how='left'
    )
    .groupby('nconst')
    .agg({
        'runtimeMinutes': 'sum',
        'tconst': 'count'
    })
    .rename(columns={'runtimeMinutes': 'total_runtime_minutes', 'tconst': 'participation_count'})
    .reset_index()
    .sort_values('total_runtime_minutes', ascending=False, na_position='last')
    .merge(dim_person, on='nconst',  how='left')
    .dropna(subset=['total_runtime_minutes'])
    .head(20)
)
# 1. Merge all your data together
full_df = (
    actors_runtime[['primaryName', 'total_runtime_minutes', 'participation_count', 'birthYear', 'deathYear', 'nconst']]
    .merge(participations_pers[['nconst', 'tconst']], on='nconst', how='left')
    .merge(dim_title_basic[['tconst', 'primaryTitle', 'runtimeMinutes']], on='tconst', how='left')
)

# 2. Sort by nconst (the person) and runtimeMinutes (descending)
# 3. Group by nconst and take the top row for each
top_title_per_person = (
    full_df.sort_values(['nconst', 'runtimeMinutes'], ascending=[True, False])
    .groupby('nconst', as_index=False)
    .head(1)
    .reset_index(drop=True)
)
top_title_per_person = (
    top_title_per_person.sort_values('total_runtime_minutes', ascending=False)
    [['primaryName', 'primaryTitle', 'total_runtime_minutes', 'participation_count', 'birthYear', 'deathYear', 'primaryTitle', 'runtimeMinutes']]
    # .rename(columns={'primaryTitle': 'longestTitle', 'runtimeMinutes': 'longestTitleRuntimeMinutes'})
)
top_title_per_person = top_title_per_person.loc[:, ~top_title_per_person.columns.duplicated()]
top_title_per_person.to_parquet(f'{project_src}\\data\\gold\\long_runtime_title.parquet', index=False)

In [63]:
top_title_per_person

,primaryName,primaryTitle,total_runtime_minutes,participation_count,birthYear,deathYear,runtimeMinutes
2,Ilaiyaraaja,Veera,65649.0,1006,1943,<NA>,240.0
9,Gérard Courant,Carnets Filmés (Liste Complète),61422.0,408,1951,<NA>,28643.0
16,Shôji Sakai,Dog Star,54455.0,1001,<NA>,<NA>,125.0
19,Innovativ Kultur,Logistics,51420.0,1,<NA>,<NA>,51420.0
18,Daniel Andersson,Logistics,51420.0,1,<NA>,<NA>,51420.0
17,Erika Magnusson,Logistics,51420.0,1,<NA>,<NA>,51420.0
0,William Shakespeare,Hamlet,46232.0,530,1564,1616,242.0
11,Dong-Chun Hyeon,Echo of Love and Death,45770.0,514,<NA>,<NA>,200.0
12,Laxmikant Shantaram Kudalkar,Narasimha,43917.0,467,1937,1998,214.0
6,Brahmanandam,New,42863.0,807,1956,<NA>,200.0
15,Pyarelal Ramprasad Sharma,Narasimha,36036.0,392,1940,<NA>,214.0
7,Lou Castel,Carnets Filmés (Liste Complète),34958.0,75,1943,<NA>,28643.0
14,Mohanlal,Iniyenkilum,34168.0,348,1960,<NA>,201.0
13,Bappi Lahiri,Pyar Ke Kabil,33718.0,447,1952,<NA>,187.0
4,Jackie Berroyer,Carnets Filmés (Liste Complète),32268.0,48,1946,<NA>,28643.0
5,Jacques Bonnaffé,Carnets Filmés (Liste Complète),32168.0,41,1958,<NA>,28643.0
1,Manuel Esperón,Story of a Great Love,31675.0,384,1911,2011,155.0
3,Mammootty,Iniyenkilum,31466.0,365,1951,<NA>,201.0
10,Olivier Dazat,Carnets Filmés (Liste Complète),31397.0,31,<NA>,<NA>,28643.0
8,Ingrid Caven,Carnets Filmés (Liste Complète),31158.0,29,1938,<NA>,28643.0

## Analysis 3: Participants with More Known Participations

In [24]:
# Participants with more known participations: using bridge_kwn_titles
# Count known titles per person (using bridge_kwn_titles if available)
known_participations = (
    bridge_kwn_titles.groupby('nconst')
    .size()
    .reset_index(name='known_title_count')
    .sort_values('known_title_count', ascending=False)
    .merge(dim_person, on='nconst', how='left')
    .head(20)
)

print("Top 20 Participants with Most Known Titles:")
print(known_participations)

Top 20 Participants with Most Known Titles:
       nconst  known_title_count            primaryName  birthYear  deathYear  \
0   nm0010174                  4        Casimiro Acosta       <NA>       <NA>
1   nm0010158                  4          Alvaro Acosta       <NA>       <NA>
2   nm0010157                  4           Alpha Acosta       1973       <NA>
3   nm0010155                  4         Alberto Acosta       <NA>       <NA>
4   nm0010154                  4          Albert Acosta       <NA>       <NA>
5   nm0010153                  4         Adriana Acosta       <NA>       <NA>
6   nm0010148                  4        Tony Acosta Jr.       <NA>       <NA>
7   nm0010144                  4  Damián Acosta Esparza       <NA>       <NA>
8   nm0000033                  4       Alfred Hitchcock       1899       1980
9   nm0000032                  4        Charlton Heston       1923       2008
10  nm0000031                  4      Katharine Hepburn       1907       2003
11  nm0000030                  4         Audrey Hepburn       1929       1993
12  nm0000029                  4      Margaux Hemingway       1954       1996
13  nm0000028                  4          Rita Hayworth       1918       1987
14  nm0000027                  4          Alec Guinness       1914       2000
15  nm0000026                  4             Cary Grant       1904       1986
16  nm0000025                  4        Jerry Goldsmith       1929       2004
17  nm0000024                  4           John Gielgud       1904       2000
18  nm0000023                  4           Judy Garland       1922       1969
19  nm0000022                  4            Clark Gable       1901       1960

   profession_group_id  weighting_factor_prf
0           p_grp_9933              0.500000
1           p_grp_9917              0.500000
2           p_grp_9916              0.500000
3           p_grp_9914              0.333333
4           p_grp_9913              0.333333
5           p_grp_9912              0.500000
6           p_grp_9907              0.333333
7           p_grp_9904              0.333333
8             p_grp_33              0.333333
9             p_grp_32              0.333333
10            p_grp_31              0.333333
11            p_grp_30              0.500000
12            p_grp_29              0.500000
13            p_grp_28              0.333333
14            p_grp_27              0.333333
15            p_grp_26              0.333333
16            p_grp_25              0.333333
17            p_grp_24              0.333333
18            p_grp_23              0.500000
19            p_grp_22              0.333333

## Analysis 4: Participants with More Distinct Genres

In [50]:
# Participants with more distinct genres worked with
# Join participations with genres through title
participants_genres = (
    participations_pers.merge(bridge_genres, on='tconst', how='inner')
    .groupby('nconst')['genre_id']
    .nunique()
    .reset_index(name='distinct_genres_count')
    .sort_values('distinct_genres_count', ascending=False)
    .merge(dim_person[[ 'primaryName' , 'birthYear', 'deathYear', 'nconst']], on='nconst', how='left')
    .head(20)
)

# print("Top 20 Participants with Most Distinct Genres:")
# print(participants_genres)
participants_genres

,nconst,distinct_genres_count,primaryName,birthYear,deathYear
0,nm0001637,27,Vincent Price,1911,1993
1,nm0001682,25,Mickey Rooney,1920,2014
2,nm0000616,25,Eric Roberts,1956,<NA>
3,nm0000799,25,Edward Asner,1929,<NA>
4,nm0000191,24,Ewan McGregor,1971,<NA>
5,nm0000165,24,Ron Howard,1954,<NA>
6,nm0000277,24,Richard Attenborough,1923,2014
7,nm0000407,24,Vivica A. Fox,1964,<NA>
8,nm0000553,24,Liam Neeson,1952,<NA>
9,nm0000308,24,Ernest Borgnine,1917,2012
10,nm0000549,23,Roger Moore,1927,2017
11,nm0000598,23,Dennis Quaid,1954,<NA>
12,nm0000158,23,Tom Hanks,1956,<NA>
13,nm0001002,23,Dean Cain,1966,<NA>
14,nm0290556,23,James Franco,1978,<NA>
15,nm0000469,23,James Earl Jones,1931,<NA>
16,nm0291918,23,Peter Franzén,1971,<NA>
17,nm1374980,23,Zac Efron,1987,<NA>
18,nm0000840,23,Lucille Ball,1911,1989
19,nm0451321,23,Shah Rukh Khan,1965,<NA>